// Generated by scripts/build_survey_package.py. Do not edit by hand.
export const SURVEY_ITEMS = {
  "bart_cnn_0001": {
    "task": "bart_cnn",
    "sample_id": "bart_cnn_5290"
  },
  "bart_cnn_0002": {
    "task": "bart_cnn",
    "sample_id": "bart_cnn_6915"
  },
  "bart_cnn_0003": {
    "task": "bart_cnn",
    "sample_id": "bart_cnn_219"
  },
  "bart_cnn_0004": {
    "task": "bart_cnn",
    "sample_id": "bart_cnn_3573"
  },
  "bart_cnn_0005": {
    "task": "bart_cnn",
    "sample_id": "bart_cnn_9464"
  },
  "bart_cnn_0006": {
    "task": "bart_cnn",
    "sample_id": "bart_cnn_7929"
  },
  "bart_cnn_0007": {
    "task": "bart_cnn",
    "sample_id": "bart_cnn_4541"
  },
  "bart_cnn_0008": {
    "task": "bart_cnn",
    "sample_id": "bart_cnn_2540"
  },
  "bart_cnn_0009": {
    "task": "bart_cnn",
    "sample_id": "bart_cnn_10226"
  },
  "bart_cnn_0010": {
    "task": "bart_cnn",
    "sample_id": "bart_cnn_7523"
  },
  "bart_cnn_0011": {
    "task": "bart_cnn",
    "sample_id": "bart_cnn_2775"
  },
  "bart_cnn_0012": {
    "task": "bart_cnn",
    "sample_id": "bart_cnn_5343"
  },
  "bart_cnn_0013": {
    "task": "bart_cnn",
    "sample_id": "bart_cnn_3010"
  },
  "bart_cnn_0014": {
    "task": "bart_cnn",
    "sample_id": "bart_cnn_6583"
  },
  "bart_cnn_0015": {
    "task": "bart_cnn",
    "sample_id": "bart_cnn_10995"
  },
  "bart_cnn_0016": {
    "task": "bart_cnn",
    "sample_id": "bart_cnn_288"
  },
  "bart_cnn_0017": {
    "task": "bart_cnn",
    "sample_id": "bart_cnn_10118"
  },
  "bart_cnn_0018": {
    "task": "bart_cnn",
    "sample_id": "bart_cnn_956"
  },
  "bart_cnn_0019": {
    "task": "bart_cnn",
    "sample_id": "bart_cnn_10083"
  },
  "bart_cnn_0020": {
    "task": "bart_cnn",
    "sample_id": "bart_cnn_7309"
  },
  "bart_cnn_0021": {
    "task": "bart_cnn",
    "sample_id": "bart_cnn_6564"
  },
  "bart_cnn_0022": {
    "task": "bart_cnn",
    "sample_id": "bart_cnn_6098"
  },
  "bart_cnn_0023": {
    "task": "bart_cnn",
    "sample_id": "bart_cnn_10935"
  },
  "bart_cnn_0024": {
    "task": "bart_cnn",
    "sample_id": "bart_cnn_10729"
  },
  "bart_cnn_0025": {
    "task": "bart_cnn",
    "sample_id": "bart_cnn_7334"
  },
  "bart_cnn_0026": {
    "task": "bart_cnn",
    "sample_id": "bart_cnn_751"
  },
  "bart_cnn_0027": {
    "task": "bart_cnn",
    "sample_id": "bart_cnn_1249"
  },
  "bart_cnn_0028": {
    "task": "bart_cnn",
    "sample_id": "bart_cnn_5860"
  },
  "bart_cnn_0029": {
    "task": "bart_cnn",
    "sample_id": "bart_cnn_2477"
  },
  "bart_cnn_0030": {
    "task": "bart_cnn",
    "sample_id": "bart_cnn_2680"
  },
  "bart_cnn_0031": {
    "task": "bart_cnn",
    "sample_id": "bart_cnn_10603"
  },
  "bart_cnn_0032": {
    "task": "bart_cnn",
    "sample_id": "bart_cnn_1757"
  },
  "bart_cnn_0033": {
    "task": "bart_cnn",
    "sample_id": "bart_cnn_8870"
  },
  "bart_cnn_0034": {
    "task": "bart_cnn",
    "sample_id": "bart_cnn_9172"
  },
  "bart_cnn_0035": {
    "task": "bart_cnn",
    "sample_id": "bart_cnn_5919"
  },
  "bart_cnn_0036": {
    "task": "bart_cnn",
    "sample_id": "bart_cnn_3439"
  },
  "bart_cnn_0037": {
    "task": "bart_cnn",
    "sample_id": "bart_cnn_3689"
  },
  "bart_cnn_0038": {
    "task": "bart_cnn",
    "sample_id": "bart_cnn_10981"
  },
  "bart_cnn_0039": {
    "task": "bart_cnn",
    "sample_id": "bart_cnn_2635"
  },
  "bart_cnn_0040": {
    "task": "bart_cnn",
    "sample_id": "bart_cnn_1947"
  },
  "bart_cnn_0041": {
    "task": "bart_cnn",
    "sample_id": "bart_cnn_6352"
  },
  "bart_cnn_0042": {
    "task": "bart_cnn",
    "sample_id": "bart_cnn_7408"
  },
  "bart_cnn_0043": {
    "task": "bart_cnn",
    "sample_id": "bart_cnn_880"
  },
  "bart_cnn_0044": {
    "task": "bart_cnn",
    "sample_id": "bart_cnn_10154"
  },
  "bart_cnn_0045": {
    "task": "bart_cnn",
    "sample_id": "bart_cnn_4529"
  },
  "bart_cnn_0046": {
    "task": "bart_cnn",
    "sample_id": "bart_cnn_5586"
  },
  "bart_cnn_0047": {
    "task": "bart_cnn",
    "sample_id": "bart_cnn_6517"
  },
  "bart_cnn_0048": {
    "task": "bart_cnn",
    "sample_id": "bart_cnn_4702"
  },
  "bart_cnn_0049": {
    "task": "bart_cnn",
    "sample_id": "bart_cnn_8396"
  },
  "bart_cnn_0050": {
    "task": "bart_cnn",
    "sample_id": "bart_cnn_5214"
  },
  "llama_cnn_0001": {
    "task": "llama_cnn",
    "sample_id": "llama_cnn_5791"
  },
  "llama_cnn_0002": {
    "task": "llama_cnn",
    "sample_id": "llama_cnn_9273"
  },
  "llama_cnn_0003": {
    "task": "llama_cnn",
    "sample_id": "llama_cnn_10364"
  },
  "llama_cnn_0004": {
    "task": "llama_cnn",
    "sample_id": "llama_cnn_5232"
  },
  "llama_cnn_0005": {
    "task": "llama_cnn",
    "sample_id": "llama_cnn_3665"
  },
  "llama_cnn_0006": {
    "task": "llama_cnn",
    "sample_id": "llama_cnn_801"
  },
  "llama_cnn_0007": {
    "task": "llama_cnn",
    "sample_id": "llama_cnn_1378"
  },
  "llama_cnn_0008": {
    "task": "llama_cnn",
    "sample_id": "llama_cnn_9388"
  },
  "llama_cnn_0009": {
    "task": "llama_cnn",
    "sample_id": "llama_cnn_3635"
  },
  "llama_cnn_0010": {
    "task": "llama_cnn",
    "sample_id": "llama_cnn_643"
  },
  "llama_cnn_0011": {
    "task": "llama_cnn",
    "sample_id": "llama_cnn_7422"
  },
  "llama_cnn_0012": {
    "task": "llama_cnn",
    "sample_id": "llama_cnn_473"
  },
  "llama_cnn_0013": {
    "task": "llama_cnn",
    "sample_id": "llama_cnn_10393"
  },
  "llama_cnn_0014": {
    "task": "llama_cnn",
    "sample_id": "llama_cnn_2987"
  },
  "llama_cnn_0015": {
    "task": "llama_cnn",
    "sample_id": "llama_cnn_6933"
  },
  "llama_cnn_0016": {
    "task": "llama_cnn",
    "sample_id": "llama_cnn_8116"
  },
  "llama_cnn_0017": {
    "task": "llama_cnn",
    "sample_id": "llama_cnn_4241"
  },
  "llama_cnn_0018": {
    "task": "llama_cnn",
    "sample_id": "llama_cnn_5689"
  },
  "llama_cnn_0019": {
    "task": "llama_cnn",
    "sample_id": "llama_cnn_2200"
  },
  "llama_cnn_0020": {
    "task": "llama_cnn",
    "sample_id": "llama_cnn_6348"
  },
  "llama_cnn_0021": {
    "task": "llama_cnn",
    "sample_id": "llama_cnn_4620"
  },
  "llama_cnn_0022": {
    "task": "llama_cnn",
    "sample_id": "llama_cnn_8679"
  },
  "llama_cnn_0023": {
    "task": "llama_cnn",
    "sample_id": "llama_cnn_11192"
  },
  "llama_cnn_0024": {
    "task": "llama_cnn",
    "sample_id": "llama_cnn_9714"
  },
  "llama_cnn_0025": {
    "task": "llama_cnn",
    "sample_id": "llama_cnn_8002"
  },
  "llama_cnn_0026": {
    "task": "llama_cnn",
    "sample_id": "llama_cnn_8763"
  },
  "llama_cnn_0027": {
    "task": "llama_cnn",
    "sample_id": "llama_cnn_3656"
  },
  "llama_cnn_0028": {
    "task": "llama_cnn",
    "sample_id": "llama_cnn_4269"
  },
  "llama_cnn_0029": {
    "task": "llama_cnn",
    "sample_id": "llama_cnn_7857"
  },
  "llama_cnn_0030": {
    "task": "llama_cnn",
    "sample_id": "llama_cnn_7403"
  },
  "llama_cnn_0031": {
    "task": "llama_cnn",
    "sample_id": "llama_cnn_8233"
  },
  "llama_cnn_0032": {
    "task": "llama_cnn",
    "sample_id": "llama_cnn_4772"
  },
  "llama_cnn_0033": {
    "task": "llama_cnn",
    "sample_id": "llama_cnn_3280"
  },
  "llama_cnn_0034": {
    "task": "llama_cnn",
    "sample_id": "llama_cnn_39"
  },
  "llama_cnn_0035": {
    "task": "llama_cnn",
    "sample_id": "llama_cnn_7313"
  },
  "llama_cnn_0036": {
    "task": "llama_cnn",
    "sample_id": "llama_cnn_2907"
  },
  "llama_cnn_0037": {
    "task": "llama_cnn",
    "sample_id": "llama_cnn_10446"
  },
  "llama_cnn_0038": {
    "task": "llama_cnn",
    "sample_id": "llama_cnn_2490"
  },
  "llama_cnn_0039": {
    "task": "llama_cnn",
    "sample_id": "llama_cnn_6645"
  },
  "llama_cnn_0040": {
    "task": "llama_cnn",
    "sample_id": "llama_cnn_7307"
  },
  "llama_cnn_0041": {
    "task": "llama_cnn",
    "sample_id": "llama_cnn_8990"
  },
  "llama_cnn_0042": {
    "task": "llama_cnn",
    "sample_id": "llama_cnn_7539"
  },
  "llama_cnn_0043": {
    "task": "llama_cnn",
    "sample_id": "llama_cnn_780"
  },
  "llama_cnn_0044": {
    "task": "llama_cnn",
    "sample_id": "llama_cnn_2659"
  },
  "llama_cnn_0045": {
    "task": "llama_cnn",
    "sample_id": "llama_cnn_412"
  },
  "llama_cnn_0046": {
    "task": "llama_cnn",
    "sample_id": "llama_cnn_2834"
  },
  "llama_cnn_0047": {
    "task": "llama_cnn",
    "sample_id": "llama_cnn_1881"
  },
  "llama_cnn_0048": {
    "task": "llama_cnn",
    "sample_id": "llama_cnn_859"
  },
  "llama_cnn_0049": {
    "task": "llama_cnn",
    "sample_id": "llama_cnn_6550"
  },
  "llama_cnn_0050": {
    "task": "llama_cnn",
    "sample_id": "llama_cnn_5574"
  }
};

export const ASSIGNMENTS = {
  "annotator_01": [
    "bart_cnn_0006",
    "bart_cnn_0026",
    "bart_cnn_0044",
    "llama_cnn_0009",
    "llama_cnn_0029"
  ],
  "annotator_02": [
    "bart_cnn_0019",
    "bart_cnn_0024",
    "bart_cnn_0035",
    "llama_cnn_0011",
    "llama_cnn_0048"
  ],
  "annotator_03": [
    "bart_cnn_0007",
    "bart_cnn_0020",
    "bart_cnn_0034",
    "llama_cnn_0007",
    "llama_cnn_0039"
  ],
  "annotator_04": [
    "bart_cnn_0009",
    "bart_cnn_0012",
    "bart_cnn_0049",
    "llama_cnn_0023",
    "llama_cnn_0044"
  ],
  "annotator_05": [
    "bart_cnn_0005",
    "bart_cnn_0015",
    "bart_cnn_0042",
    "llama_cnn_0017",
    "llama_cnn_0047"
  ],
  "annotator_06": [
    "bart_cnn_0016",
    "bart_cnn_0031",
    "bart_cnn_0046",
    "llama_cnn_0045",
    "llama_cnn_0046"
  ],
  "annotator_07": [
    "bart_cnn_0018",
    "bart_cnn_0027",
    "bart_cnn_0029",
    "llama_cnn_0015",
    "llama_cnn_0049"
  ],
  "annotator_08": [
    "bart_cnn_0002",
    "bart_cnn_0010",
    "bart_cnn_0021",
    "llama_cnn_0003",
    "llama_cnn_0018"
  ],
  "annotator_09": [
    "bart_cnn_0008",
    "bart_cnn_0023",
    "bart_cnn_0030",
    "llama_cnn_0005",
    "llama_cnn_0026"
  ],
  "annotator_10": [
    "bart_cnn_0017",
    "bart_cnn_0041",
    "bart_cnn_0043",
    "llama_cnn_0013",
    "llama_cnn_0038"
  ],
  "annotator_11": [
    "bart_cnn_0032",
    "bart_cnn_0047",
    "llama_cnn_0031",
    "llama_cnn_0037",
    "llama_cnn_0043"
  ],
  "annotator_12": [
    "bart_cnn_0022",
    "bart_cnn_0037",
    "llama_cnn_0022",
    "llama_cnn_0024",
    "llama_cnn_0042"
  ],
  "annotator_13": [
    "bart_cnn_0013",
    "bart_cnn_0033",
    "llama_cnn_0014",
    "llama_cnn_0033",
    "llama_cnn_0040"
  ],
  "annotator_14": [
    "bart_cnn_0004",
    "bart_cnn_0045",
    "llama_cnn_0010",
    "llama_cnn_0032",
    "llama_cnn_0041"
  ],
  "annotator_15": [
    "bart_cnn_0014",
    "bart_cnn_0040",
    "llama_cnn_0019",
    "llama_cnn_0020",
    "llama_cnn_0028"
  ],
  "annotator_16": [
    "bart_cnn_0039",
    "bart_cnn_0050",
    "llama_cnn_0030",
    "llama_cnn_0036",
    "llama_cnn_0050"
  ],
  "annotator_17": [
    "bart_cnn_0011",
    "bart_cnn_0048",
    "llama_cnn_0002",
    "llama_cnn_0006",
    "llama_cnn_0012"
  ],
  "annotator_18": [
    "bart_cnn_0003",
    "bart_cnn_0025",
    "llama_cnn_0001",
    "llama_cnn_0025",
    "llama_cnn_0027"
  ],
  "annotator_19": [
    "bart_cnn_0028",
    "bart_cnn_0036",
    "llama_cnn_0008",
    "llama_cnn_0016",
    "llama_cnn_0021"
  ],
  "annotator_20": [
    "bart_cnn_0001",
    "bart_cnn_0038",
    "llama_cnn_0004",
    "llama_cnn_0034",
    "llama_cnn_0035"
  ]
};
